/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nicole
 */
public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form signupFrame
     */
    public SignupForm() {
        initComponents();
        
        jPanelHr.setVisible(false);
        jPanelSal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jPanelRegister = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelPass = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jLabelRePass = new javax.swing.JLabel();
        jPasswordFieldRe = new javax.swing.JPasswordField();
        jCheckBoxShowRePass = new javax.swing.JCheckBox();
        jRadioSalary = new javax.swing.JRadioButton();
        jRadioHourly = new javax.swing.JRadioButton();
        jCheckBoxDebt = new javax.swing.JCheckBox();
        jLabelNumAcc = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLayeredMoney = new javax.swing.JLayeredPane();
        jPanelHr = new javax.swing.JPanel();
        jLabelHourly = new javax.swing.JLabel();
        jTextPaneHourly = new javax.swing.JTextPane();
        jTextPaneHours = new javax.swing.JTextPane();
        jLabelHours = new javax.swing.JLabel();
        jPanelSal = new javax.swing.JPanel();
        jLabelSalary = new javax.swing.JLabel();
        jTextPaneSalary = new javax.swing.JTextPane();
        jRadioBi = new javax.swing.JRadioButton();
        jRadioWk = new javax.swing.JRadioButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create New Account");
        setPreferredSize(new java.awt.Dimension(612, 732));
        setResizable(false);

        jPanelTop.setBackground(new java.awt.Color(122, 207, 10));

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelRegister.setBackground(new java.awt.Color(57, 80, 103));
        jPanelRegister.setPreferredSize(new java.awt.Dimension(604, 676));

        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Name");

        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("Username");

        jLabelPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPass.setText("Password");

        jCheckBoxShowPass.setFont(new java.awt.Font("Phetsarath OT", 0, 18)); // NOI18N
        jCheckBoxShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowPass.setText("Show Pass");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });

        jLabelRePass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRePass.setText("Retype Password");

        jCheckBoxShowRePass.setFont(new java.awt.Font("Phetsarath OT", 0, 18)); // NOI18N
        jCheckBoxShowRePass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowRePass.setText("Show Pass");
        jCheckBoxShowRePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowRePassActionPerformed(evt);
            }
        });

        jRadioSalary.setForeground(new java.awt.Color(255, 255, 255));
        jRadioSalary.setText("Salary");
        jRadioSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSalaryActionPerformed(evt);
            }
        });

        jRadioHourly.setForeground(new java.awt.Color(255, 255, 255));
        jRadioHourly.setText("Hourly Wage");
        jRadioHourly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioHourlyActionPerformed(evt);
            }
        });

        jCheckBoxDebt.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxDebt.setText("Apply Debt");
        jCheckBoxDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDebtActionPerformed(evt);
            }
        });

        jLabelNumAcc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumAcc.setText("Number of Bank Accounts");

        jLayeredMoney.setBackground(new java.awt.Color(142, 182, 223));
        jLayeredMoney.setLayout(new javax.swing.OverlayLayout(jLayeredMoney));

        jPanelHr.setBackground(new java.awt.Color(57, 80, 103));

        jLabelHourly.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHourly.setText("Hourly Wage");

        jLabelHours.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHours.setText("Hours Worked");

        javax.swing.GroupLayout jPanelHrLayout = new javax.swing.GroupLayout(jPanelHr);
        jPanelHr.setLayout(jPanelHrLayout);
        jPanelHrLayout.setHorizontalGroup(
            jPanelHrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHourly)
                .addGap(29, 29, 29)
                .addComponent(jTextPaneHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelHours)
                .addGap(18, 18, 18)
                .addComponent(jTextPaneHours, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelHrLayout.setVerticalGroup(
            jPanelHrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPaneHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHours)
                    .addComponent(jTextPaneHourly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHourly))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredMoney.add(jPanelHr);

        jPanelSal.setBackground(new java.awt.Color(57, 80, 103));
        jPanelSal.setPreferredSize(new java.awt.Dimension(329, 100));

        jLabelSalary.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalary.setText("Gross Salary");

        javax.swing.GroupLayout jPanelSalLayout = new javax.swing.GroupLayout(jPanelSal);
        jPanelSal.setLayout(jPanelSalLayout);
        jPanelSalLayout.setHorizontalGroup(
            jPanelSalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalary)
                .addGap(33, 33, 33)
                .addComponent(jTextPaneSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanelSalLayout.setVerticalGroup(
            jPanelSalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSalary)
                    .addComponent(jTextPaneSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredMoney.add(jPanelSal);

        jRadioBi.setForeground(new java.awt.Color(255, 255, 255));
        jRadioBi.setText("Bi-weekly pay");
        jRadioBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBiActionPerformed(evt);
            }
        });

        jRadioWk.setForeground(new java.awt.Color(255, 255, 255));
        jRadioWk.setText("Weekly pay");
        jRadioWk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioWkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("Already have an account? Login!");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxShowPass))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabelLogin))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLayeredMoney, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioHourly))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                            .addComponent(jPasswordFieldRe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jCheckBoxShowRePass))
                                        .addComponent(jRadioSalary)))
                                .addComponent(jCheckBoxDebt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegisterLayout.createSequentialGroup()
                                .addComponent(jLabelNumAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioBi)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioWk)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxShowPass))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxShowRePass))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioHourly)
                    .addComponent(jRadioSalary))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxDebt)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLayeredMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBi)
                    .addComponent(jRadioWk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDebtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDebtActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jRadioHourlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioHourlyActionPerformed
        // TODO add your handling code here:
        jRadioHourly.setSelected(true);
        jRadioSalary.setSelected(false);
        
        jPanelHr.setVisible(true);
        jPanelSal.setVisible(false);
        
    }//GEN-LAST:event_jRadioHourlyActionPerformed

    private void jRadioSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSalaryActionPerformed
        // TODO add your handling code here:
        jRadioHourly.setSelected(false);
        jRadioSalary.setSelected(true);
        
        jPanelHr.setVisible(false);
        jPanelSal.setVisible(true);
    }//GEN-LAST:event_jRadioSalaryActionPerformed

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxShowPass.isSelected()){
            jPasswordField.setEchoChar((char)0);
        }else{
            jPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    private void jCheckBoxShowRePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowRePassActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxShowRePass.isSelected()){
            jPasswordFieldRe.setEchoChar((char)0);
        }else{
            jPasswordFieldRe.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowRePassActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        LoginForm loginF = new LoginForm();
        loginF.setVisible(true);
        loginF.pack();
        loginF.setLocationRelativeTo(null);
        loginF.setDefaultCloseOperation(EXIT_ON_CLOSE);//Closes both forms not just one
        this.dispose();//Pops up only other form - og goes away
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jRadioBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBiActionPerformed

    private void jRadioWkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioWkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioWkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JCheckBox jCheckBoxDebt;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JCheckBox jCheckBoxShowRePass;
    private javax.swing.JLabel jLabelHourly;
    private javax.swing.JLabel jLabelHours;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumAcc;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelRePass;
    private javax.swing.JLabel jLabelSalary;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLayeredPane jLayeredMoney;
    private javax.swing.JPanel jPanelHr;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPanel jPanelSal;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldRe;
    private javax.swing.JRadioButton jRadioBi;
    private javax.swing.JRadioButton jRadioHourly;
    private javax.swing.JRadioButton jRadioSalary;
    private javax.swing.JRadioButton jRadioWk;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JTextPane jTextPaneHourly;
    private javax.swing.JTextPane jTextPaneHours;
    private javax.swing.JTextPane jTextPaneSalary;
    // End of variables declaration//GEN-END:variables
}
